# Generated by Django 4.2.1 on 2025-01-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='team',
        ),
    ]
