# Generated by Django 4.2.1 on 2025-01-23 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_alter_team_comment'),
        ('comments', '0002_remove_comment_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='teams.team'),
        ),
    ]
