# Generated by Django 4.2.1 on 2024-12-28 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='achievement',
            field=models.CharField(choices=[('team_of_the_month', 'Team of the Month'), ('team_of_the_year', 'Team of the Year'), ('team_of_the_decade', 'Team of the Decade'), ('speedster', 'Speedster'), ('team_with_the_highest_rating', 'Team with the Highest Rating'), ('the_team_that_completed_the_most_tasks', 'The Team That Completed the Most Tasks')], default='No achievements', max_length=150),
        ),
        migrations.AddField(
            model_name='team',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='rank',
            field=models.CharField(choices=[('junior_team', 'Junior Team'), ('pro_team', 'Pro Team'), ('expert_team', 'Expert Team')], default='junior_team', max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='tasks_completed',
            field=models.IntegerField(default=0),
        ),
    ]
