# Generated by Django 4.2.1 on 2024-12-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_alter_space_teams'),
        ('teams', '0002_team_achievement_team_owner_id_team_rank_team_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='spaces',
            field=models.ManyToManyField(related_name='teams_in_space', to='spaces.space'),
        ),
    ]
