# Generated by Django 4.2.1 on 2024-12-28 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0006_remove_space_teams'),
        ('teams', '0003_team_spaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='spaces',
        ),
        migrations.AddField(
            model_name='team',
            name='space_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaces.space'),
        ),
    ]
