# Generated by Django 4.2.1 on 2024-12-28 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_spaces_team_space_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='space_id',
        ),
    ]
