# Generated by Django 4.2.1 on 2025-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('teams', '0005_remove_team_space_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='teams', to='comments.comment'),
        ),
    ]
