# Generated by Django 4.2.1 on 2025-01-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_remove_comment_team'),
        ('teams', '0006_team_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='teams', to='comments.comment'),
        ),
    ]
