# Generated by Django 4.2.1 on 2024-12-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='spaces_count',
            field=models.IntegerField(default=0),
        ),
    ]
