# Generated by Django 4.2.1 on 2024-12-25 22:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spaces', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(null=True, related_name='spaces', to=settings.AUTH_USER_MODEL),
        ),
    ]
