# Generated by Django 4.2.1 on 2024-12-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('spaces', '0003_alter_space_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='teams.team'),
        ),
    ]
