# Generated by Django 4.2.1 on 2024-12-28 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_team_achievement_team_owner_id_team_rank_team_score_and_more'),
        ('spaces', '0004_space_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='spaces_in_space', to='teams.team'),
        ),
    ]
