# Generated by Django 4.2.1 on 2024-12-28 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaces', '0005_alter_space_teams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='teams',
        ),
    ]
