# Generated by Django 4.2.1 on 2024-12-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_remove_team_space_id'),
        ('spaces', '0006_remove_space_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='teams.team'),
        ),
    ]
